### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by mfclarke** [typhoeus/ethon#113]
I'm still kinda new to memory troubleshooting in Ruby, but I think I may have found a leak in Ethon. I profile using the following code and the ```memory_profiler``` gem.

```
5.times do
  request = Ethon::Easy.new(url: "www.example.com")
  request.perform
end

GC.start

MemoryProfiler.report do
  5.times do
    request = Ethon::Easy.new(url: "www.example.com")
    request.perform
  end
  GC.start
end.pretty_print
```

It shows the following as still retained:

```
retained memory by gem
-----------------------------------
      1272  ethon-0.8.0
       400  ffi-1.9.10
       400  other

retained memory by file
-----------------------------------
       872  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/easy/operations.rb
       400  (irb)
       400  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ffi-1.9.10/lib/ffi/autopointer.rb
       320  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/curls/options.rb
        80  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/easy.rb
````

Doesn't seem like much, but when you're using Hydra... It stacks up. Testing with Hydra doing 100 requests to a local webserver with a more full html page, it clocks up to this:

```
retained memory by gem
-----------------------------------
    438465  ethon-0.8.0
    289924  ffi-1.9.10
      3374  2.2.3/lib
      3256  other
      2310  activesupport-4.2.0

retained memory by file
-----------------------------------
    383784  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/easy/callbacks.rb
    273924  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ffi-1.9.10/lib/ffi/pointer.rb
     30403  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/easy/operations.rb
     16000  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ffi-1.9.10/lib/ffi/autopointer.rb
      8856  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/easy/mirror.rb
      8714  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/easy.rb
      6308  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/curls/options.rb
      3256  (irb)
      2550  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/2.2.0/logger.rb
      1590  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/logger.rb
       824  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/2.2.0/pp.rb
       480  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/numeric/conversions.rb
       240  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb
       240  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/curls/infos.rb
       160  /Users/maxclarke/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ethon-0.8.0/lib/ethon/easy/debug_info.rb
```

For my use case, which involves a bit of responsible web scraping, this gets a bit more significant!

**Comment by Zapotek** [comment]
Is it a leak though or just plain usage?

Because the files that use the most memory are the ones reading the responses from the server (well, the ones reading the responses from libcurl via FFI to be precise) so it's normal that these will have greater memory usage.

The [reading of the response body](https://github.com/typhoeus/ethon/blob/master/lib/ethon/easy/callbacks.rb#L100) may benefit from using destructive methods (for example `slice!` instead of `String#[]`) to avoid creating more objects though.

Still, I don't think that memory is leaking, spiking yes, but the allocated memory should end up being reused by the interpreter.

I'm mostly speaking from experience, a leak of this type would jump out in [Arachni](https://github.com/Arachni/arachni).

**Comment by Zapotek** [comment]
I forgot to mention, try traversing the object space and counting the `Typhoeus::Request` and `Typhoeus::Response` objects, usually whenever I think that Typhoeus is leaking, it turns out that I'm hanging on to these objects more than I should.

**Comment by mfclarke** [comment]
Hmmm, that makes sense. I'm going to do some further research - sounds like this basic profiling might be too simple and quick for FFI. It could be that FFI hasn't had a chance to release stuff yet, or the pointer gets reused.

Either way, your real world experience with Arachni is definitely making me think twice about this. Thanks for your explanation @Zapotek.

**Comment by Zapotek** [comment]
I think the fact that MRI prefers to reuse allocated memory rather than free it has more to do with this, regardless of where that allocation occurs.

If you observe your script with `top` you'll see memory usage spikes which never go down (+- a few MB), but at some point memory usage stops growing and the program just uses the memory that has been allocated thus far.

This is basically to avoid having to constantly hammer the kernel with `free()` and `malloc()` calls every time an object is created or destroyed, which as you can imagine happens **a lot**.

Of course, if memory consumption never stabilizes but instead keeps on growing then yeah, there's a leak somewhere.

Another pattern you may wish to use while working with `Hydra` is to wrap it as your own client in order to enforce a max limit of queued requests and call `Hydra#run` upon reaching that limit.
The magic numbers I use are a max concurrency of 20 with a max request queue size of 100, you get pretty good performance and reasonable memory usage.

**Comment by i0rek** [comment]
@mfclarke thanks for reporting! @Zapotek thanks for your help!
In general it is very much possible that Ethon leaks memory, it happened before. Let me know if you find more evidence :)

**Comment by Zapotek** [comment]
@mfclarke I was looking at the `memory_profiler` gem and came across this:
https://github.com/SamSaffron/memory_profiler/blob/master/lib/memory_profiler/reporter.rb#L33-L44

While the code you're profiling is running, garbage collection is disabled; so if you decide to let your code run for a while and monitor it from something like `top`, don't use the `memory_profiler` gem at the same time because it'd look like there's a huge leak.

**Comment by mfclarke** [comment]
@Zapotek You're right - if I don't wrap the 5.times (or 100+ times in the case of testing against a local webserver) in a memory_profiler ```report``` block then the memory stabilises.

And on a related note, the bigger picture for me is a longer script using Hydra for data fetching. If I break this script into pieces so objects and arrays fall out of scope when they're not needed, then the GC does a better job of cleaning up and my memory is much more under control now. You live and you learn :)

**Comment by Zapotek** [comment]
@mfclarke That's how GC works in general, it only collects out of scope objects. If you keep stuff around then they'll never be collected and their memory will never get reused, you'll just end up allocating more and more memory as the script runs to accommodate all the objects you hold on to.

So, did that change fix your issue or are you still experiencing abnormal behavior from Ethon?

**Comment by mfclarke** [comment]
@Zapotek Yes, my issue is now resolved. Thanks again for your help
