### ISSUE TITLE
Unlimited ulimit on max open blows up

### ISSUE THREAD

**Issue by ucjonathan** [typhoeus/ethon#182]
In classes.rb on line 36, this code will blow up in Digital Ocean because the max open file limit is a massive value.

FD_SETSIZE = ::Ethon::Libc.sysconf(:open_max)
layout :fds_bits, [:long, FD_SETSIZE / ::FFI::Type::LONG.size]

I recommend having some sane upper bound before calling the layout function so that ethon doesn't explode.  We found this error running a Swagger codegen Ruby SDK that depends on the ethon library.

**Comment by jcodybaker** [comment]
As a workaround until this is fixed, you can adjust the open file limit to a lower value with `ulimit -n 65535`.  The error often seen with this is:
```
1.15.0/lib/ffi/struct_layout_builder.rb:171:in `initialize': integer 4294967288 too big to convert to `int' (RangeError)
```

**Comment by mttkay** [comment]
I ran into this issue when running the GitLab Rails app in a Docker container. In this case, `sizeof FDSet` was 1GB since `ulimit -n` was `1073741816`. 

I was able to work around this by changing the default limits for file descriptors in the Docker daemon config:

```json
{
  "default-ulimits": {
    "nofile": {
      "Hard": 64000,
      "Name": "nofile",
      "Soft": 64000
    }
  }
}
```

I agree with the previous comments that this should have a sensible cap on it. Since this allocated memory outside the Ruby heap, it does not come up in memory reports that query the Ruby GC, which makes it difficult to diagnose.

https://gitlab.com/gitlab-org/gitlab-compose-kit/-/issues/65

**Comment by Kjarrigan** [comment]
@mttkay Something like this #214 ?

**Comment by Kjarrigan** [comment]
Merged. 

> Sorry for the late response -- I'm traveling this week

No worries. I'm a bit short on time myself. Travel safe!

**Comment by mttkay** [comment]
Excellent, thanks!

**Comment by hatricker** [comment]
@Kjarrigan, are we going to cut a new release/tag anytime soon? Thanks.
